package com.ongi.api.admin.web.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public record GovernmentNutritionRecord(
	@JsonProperty("식품코드") String 식품코드,
	@JsonProperty("식품명") String 식품명,
	@JsonProperty("데이터구분코드") String 데이터구분코드,
	@JsonProperty("데이터구분명") String 데이터구분명,
	@JsonProperty("에너지(kcal)") String 에너지,
	@JsonProperty("영양성분함량기준량") String 영양성분함량기준량,
	@JsonProperty("수분(g)") String 수분,
	@JsonProperty("단백질(g)") String 단백질,
	@JsonProperty("지방(g)") String 지방,
	@JsonProperty("회분(g)") String 회분,
	@JsonProperty("탄수화물(g)") String 탄수화물,
	@JsonProperty("당류(g)") String 당류,
	@JsonProperty("식이섬유(g)") String 식이섬유,
	@JsonProperty("칼슘(mg)") String 칼슘,
	@JsonProperty("철(mg)") String 철분,
	@JsonProperty("인(mg)") String 인,
	@JsonProperty("칼륨(mg)") String 칼륨,
	@JsonProperty("나트륨(mg)") String 나트륨,
	@JsonProperty("비타민 A(μg RAE)") String 비타민A,
	@JsonProperty("레티놀(μg)") String 레티놀,
	@JsonProperty("베타카로틴(μg)") String 베타카로틴,
	@JsonProperty("티아민(mg)") String 티아민,
	@JsonProperty("리보플라빈(mg)") String 리보플라빈,
	@JsonProperty("니아신(mg)") String 니아신,
	@JsonProperty("비타민 C(mg)") String 비타민C,
	@JsonProperty("비타민 D(μg)") String 비타민D,
	@JsonProperty("콜레스테롤(mg)") String 콜레스테롤,
	@JsonProperty("포화지방산(g)") String 포화지방산,
	@JsonProperty("트랜스지방산(g)") String 트랜스지방산,
	@JsonProperty("폐기율(%)") String 폐기율,
	@JsonProperty("출처코드") String 출처코드,
	@JsonProperty("출처명") String 출처명,
	@JsonProperty("식품중량") String 식품중량,
	@JsonProperty("수입여부") String 수입여부,
	@JsonProperty("원산지국코드") String 원산지국코드,
	@JsonProperty("원산지국명") String 원산지국명,
	@JsonProperty("업체명") String 업체명,
	@JsonProperty("제조사명") String 제조사명,
	@JsonProperty("수입업체명") String 수입업체명,
	@JsonProperty("유통업체명") String 유통업체명,
	@JsonProperty("데이터생성방법코드") String 데이터생성방법코드,
	@JsonProperty("데이터생성방법명") String 데이터생성방법명,
	@JsonProperty("데이터생성일자") String 데이터생성일자,
	@JsonProperty("데이터기준일자") String 데이터기준일자,
	@JsonProperty("제공기관코드") String 제공기관코드,
	@JsonProperty("제공기관명") String 제공기관명
) {

}
