package com.ongi.api.common.persistence.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum OutBoxEventTypeEnum {

	RECIPE_CREATED("RECIPE_CREATED"),
	RECIPE_UPDATED("RECIPE_UPDATED"),
	RECIPE_DELETED("RECIPE_DELETED"),

	RECIPE_VIEW("RECIPE_VIEW"),

	RECIPE_LIKED("RECIPE_LIKED"),
	RECIPE_UNLIKED("RECIPE_UNLIKED"),
	RECIPE_BOOKMARKED("RECIPE_BOOKMARKED"),
	RECIPE_UNBOOKMARKED("RECIPE_UNBOOKMARKED"),

	RECIPE_COMMENT_CREATED("RECIPE_COMMENT_CREATED"),
	RECIPE_COMMENT_UPDATED("RECIPE_COMMENT_UPDATED"),
	RECIPE_COMMENT_DELETED("RECIPE_COMMENT_DELETED");

	private final String code;
}
