package com.ongi.api.common.persistence.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum OutBoxEventTypeEnum {

	RECIPE_CREATED("RECIPE_CREATED"),
	RECIPE_UPDATED("RECIPE_UPDATED"),
	RECIPE_DELETED("RECIPE_DELETED"),

	RECIPE_VIEW("RECIPE_VIEW"),

	RECIPE_LIKED("RECIPE_LIKED"),
	RECIPE_UNLIKED("RECIPE_UNLIKED"),
	RECIPE_BOOKMARKED("RECIPE_BOOKMARKED"),
	RECIPE_UNBOOKMARKED("RECIPE_UNBOOKMARKED"),

	RECIPE_COMMENT_CREATED("RECIPE_COMMENT_CREATED"),
	RECIPE_COMMENT_UPDATED("RECIPE_COMMENT_UPDATED"),
	RECIPE_COMMENT_DELETED("RECIPE_COMMENT_DELETED"),

	COMMUNITY_POST_CREATED("COMMUNITY_POST_CREATED"),
	COMMUNITY_POST_UPDATED("COMMUNITY_POST_UPDATED"),
	COMMUNITY_POST_DELETED("COMMUNITY_POST_DELETED"),
	COMMUNITY_POST_LIKED("COMMUNITY_POST_LIKED"),
	COMMUNITY_POST_UNLIKED("COMMUNITY_POST_UNLIKED"),

	COMMUNITY_POST_VIEW("COMMUNITY_POST_VIEW"),

	COMMUNITY_COMMENT_CREATED("COMMUNITY_COMMENT_CREATED"),
	COMMUNITY_COMMENT_UPDATED("COMMUNITY_COMMENT_UPDATED"),
	COMMUNITY_COMMENT_DELETED("COMMUNITY_COMMENT_DELETED"),
	COMMUNITY_COMMENT_LIKED("COMMUNITY_COMMENT_LIKED"),
	COMMUNITY_COMMENT_UNLIKED("COMMUNITY_COMMENT_UNLIKED");

	private final String code;
}
